import { formatCurrency } from '@/lib/utils';
import type { FunnelCard } from '@/types/funnel';
import { Calendar, User, DollarSign, MoreVertical, MessageCircle, TruckIcon, Check, ChevronRight } from 'lucide-react';

interface LeadCardProps {
  card: FunnelCard;
  mode: 'grid' | 'list';
  onMoveClick: (card: FunnelCard) => void;
  onEditClick: (card: FunnelCard) => void;
  onWhatsAppClick: (card: FunnelCard) => void;
  onDragHandleProps?: any; // Para o dnd-kit ou react-beautiful-dnd caso injetemos
}

export function LeadCard({ card, mode, onMoveClick, onEditClick, onWhatsAppClick, onDragHandleProps }: LeadCardProps) {
  
  const formatDate = (val: any) => {
    if (!val) return 'Não definida';
    if (typeof val === 'string') {
      const parts = val.split('-');
      if (parts.length === 3) return `${parts[2]}/${parts[1]}/${parts[0]}`;
      return val;
    }
    // assume Firestore Timestamp
    if (val.toDate) {
      return val.toDate().toLocaleDateString('pt-BR');
    }
    return 'Inválida';
  };

  const getDaysInStage = () => {
    if (!card.movedToCurrentStageAt) return 0;
    const date = typeof card.movedToCurrentStageAt === 'string' 
      ? new Date(card.movedToCurrentStageAt) 
      : card.movedToCurrentStageAt.toDate ? card.movedToCurrentStageAt.toDate() : new Date();
    
    const diff = Math.abs(new Date().getTime() - date.getTime());
    return Math.floor(diff / (1000 * 60 * 60 * 24));
  };

  const daysInStage = getDaysInStage();

  // Se tiver a função de arrastar injetada, aplicamos apenas ao botão de grip se desejado,
  // mas como toda a caixa será arrastável no desktop, isso virá de fora no wrapper Draggable.
  // Aqui apenas renderizamos o visual.
  
  // RENDER GRID (Desktop)
  if (mode === 'grid') {
    return (
      <div className="bg-surface-base border border-surface-border rounded-2xl p-4 shadow-sm hover:border-surface-hover hover:shadow-md transition-all flex flex-col gap-3 relative group">
        
        {/* Alerts Corner */}
        <div className="absolute top-3 right-3 flex gap-1">
          {card.alerts.paymentPending && <span title="Pagamento Pendente" className="w-2.5 h-2.5 rounded-full bg-danger animate-pulse" />}
          {card.alerts.teamMissing && <span title="Equipe não alocada (data próxima)" className="w-2.5 h-2.5 rounded-full bg-warning animate-pulse" />}
          {card.alerts.quoteStale && <span title="Orçamento sem resposta" className="w-2.5 h-2.5 rounded-full bg-info" />}
        </div>

        {/* Header */}
        <div>
          <h3 className="font-bold text-text-primary text-sm pr-10">{card.clientName}</h3>
          
          <div className="flex items-center gap-2 mt-1.5 flex-wrap">
            {card.eventType === 'festa' ? (
              <span className="shrink-0 bg-brand-purple/10 text-brand-purple text-[9px] font-black px-1.5 py-0.5 rounded uppercase tracking-tighter border border-brand-purple/20">
                Festa
              </span>
            ) : (
              <span className="shrink-0 bg-info/10 text-info text-[9px] font-black px-1.5 py-0.5 rounded uppercase tracking-tighter border border-info/20">
                 Colônia
              </span>
            )}
            {card.autoGenerated && (
              <span className="shrink-0 bg-brand-yellow/10 text-brand-yellow text-[9px] font-black px-1.5 py-0.5 rounded uppercase tracking-tighter border border-brand-yellow/20">
                Auto
              </span>
            )}
            {card.isVip && (
              <span className="shrink-0 bg-success/10 text-success text-[9px] font-black px-1.5 py-0.5 rounded uppercase tracking-tighter border border-success/20">
                VIP
              </span>
            )}
          </div>
        </div>

        {/* Info */}
        <div className="space-y-1.5 bg-surface-raised/50 p-2.5 rounded-xl border border-surface-border-subtle mt-1">
          <div className="flex items-center gap-2 text-xs text-text-secondary">
            <DollarSign className="w-3 h-3 text-brand-yellow shrink-0" />
            <span className="font-semibold text-text-primary">{formatCurrency(card.estimatedValue)}</span>
          </div>
          <div className="flex items-center gap-2 text-xs text-text-secondary">
            <Calendar className="w-3 h-3 text-text-muted shrink-0" />
            <span>{formatDate(card.eventDate)} {card.rawEventoInfo?.horario ? `às ${card.rawEventoInfo.horario}` : ''}</span>
          </div>
          {card.rawEventoInfo?.duracao && (
            <div className="flex items-center gap-2 text-[10px] text-text-muted">
              <span className="bg-surface-border-subtle h-[2px] w-4" />
              <span>Duração: {card.rawEventoInfo.duracao}h</span>
            </div>
          )}
        </div>

        {/* Footer (Team & Age indicator) */}
        <div className="pt-2 flex items-center justify-between mt-auto">
          
          <div className="flex items-center gap-1.5">
            {/* Mocking team avatars simply with placeholders */}
            <div className="flex -space-x-1.5">
              {card.allocatedRecreadorIds.length === 0 ? (
                <div className="w-5 h-5 rounded-full bg-surface-border flex items-center justify-center border border-surface-base">
                  <User className="w-2.5 h-2.5 text-text-muted" />
                </div>
              ) : (
                card.allocatedRecreadorIds.slice(0, 3).map((id, i) => (
                  <div key={id} className={`w-5 h-5 rounded-full flex items-center justify-center border border-surface-base text-[8px] font-bold text-white ${['bg-brand-purple', 'bg-info', 'bg-success'][i%3]}`}>
                    H
                  </div>
                ))
              )}
            </div>
            {card.allocatedRecreadorIds.length > 3 && (
              <span className="text-[10px] text-text-muted">+{card.allocatedRecreadorIds.length - 3}</span>
            )}
          </div>

          <div className="flex items-center gap-3">
            <span className={`text-[10px] font-bold ${daysInStage > 7 ? 'text-danger' : daysInStage > 4 ? 'text-warning' : 'text-text-muted'}`}>
              Há {daysInStage} {daysInStage === 1 ? 'dia' : 'dias'}
            </span>

            {/* Actions Quick Menu */}
            <div className="flex items-center gap-1 opacity-10 md:opacity-0 group-hover:opacity-100 transition-opacity">
              <button title="WhatsApp" onClick={() => onWhatsAppClick(card)} className="p-1 text-text-muted hover:text-success hover:bg-success/10 rounded">
                <MessageCircle className="w-3.5 h-3.5" />
              </button>
              <button title="Mover Estágio" onClick={() => onMoveClick(card)} className="p-1 text-text-muted hover:text-brand-purple hover:bg-brand-purple/10 rounded">
                <ChevronRight className="w-3.5 h-3.5" />
              </button>
            </div>
          </div>
        </div>
      </div>
    );
  }

  // RENDER LIST (Mobile)
  return (
    <div className="bg-surface-base border-b border-surface-border-subtle p-4 flex gap-3 items-center active:bg-surface-raised cursor-pointer touch-pan-x snap-start" onClick={() => onEditClick(card)}>
      {/* Alert Strip Left */}
      <div className="w-1 self-stretch rounded-full flex flex-col gap-1 shrink-0">
         {card.alerts.paymentPending && <div className="flex-1 bg-danger rounded-full" />}
         {card.alerts.teamMissing && <div className="flex-1 bg-warning rounded-full" />}
         {card.alerts.quoteStale && <div className="flex-1 bg-info rounded-full" />}
         {(!card.alerts.paymentPending && !card.alerts.teamMissing && !card.alerts.quoteStale) && <div className="flex-1 bg-surface-border rounded-full" />}
      </div>

      <div className="flex-1 min-w-0">
        <h4 className="font-bold text-text-primary text-sm truncate">{card.clientName}</h4>
        <div className="flex items-center gap-2 mt-1 text-[10px] uppercase font-bold tracking-widest text-text-muted">
          <span>{formatDate(card.eventDate)} {card.rawEventoInfo?.horario ? `• ${card.rawEventoInfo.horario}` : ''}</span>
          <span className="w-1 h-1 rounded-full bg-surface-border-subtle" />
          <span className="text-brand-yellow truncate">{formatCurrency(card.estimatedValue)}</span>
        </div>
      </div>
      
      {/* Botões rápidos nativos (Mover -> WhatsApp) ao invés de swipe na V1 (por facilidade de implementação sem libs pesadas de drag/swipe mobile complexas, colocamos um layout clean) */}
      <div className="shrink-0 flex gap-1">
        <button 
          onClick={(e) => { e.stopPropagation(); onWhatsAppClick(card); }}
          className="w-8 h-8 rounded bg-surface-raised text-text-muted flex items-center justify-center border border-surface-border-subtle active:scale-95"
        >
          <MessageCircle className="w-4 h-4" />
        </button>
        <button 
          onClick={(e) => { e.stopPropagation(); onMoveClick(card); }}
          className="w-8 h-8 rounded bg-brand-purple/10 text-brand-purple flex items-center justify-center border border-brand-purple/20 active:scale-95"
        >
          <ChevronRight className="w-4 h-4" />
        </button>
      </div>
    </div>
  );
}
