import type { Timestamp } from 'firebase/firestore';

export interface FunnelCard {
  id: string;
  stageId: string;
  clientName: string;
  clientPhone?: string;
  eventType: string; // 'festa' | 'colonia'
  eventDate?: Timestamp | string | null;
  estimatedValue: number;
  allocatedRecreadorIds: string[];
  isVip: boolean;
  autoGenerated: boolean;
  sourceEventId?: string;
  lostReason?: string;
  movedToCurrentStageAt?: Timestamp | string | null;
  createdAt: Timestamp | string;
  note?: string;
  alerts: {
    paymentPending: boolean;
    teamMissing: boolean;
    quoteStale: boolean;
  };
  // Store raw Evento document just in case we need to edit or fallback properties
  rawEventoInfo?: any; 
}
