import { useState, useEffect, useMemo } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { collection, onSnapshot, doc, updateDoc, serverTimestamp, query, orderBy, addDoc } from 'firebase/firestore';
import { db } from '@/lib/firebase';
import { useConfig } from '@/lib/settings';
import { calcRecontactDate, getFinalizationBlockers, isQuoteStale, isTeamAlert } from '@/lib/automations';
import { formatCurrency } from '@/lib/utils';
import { Button } from '@/components/ui/Button';
import { Modal } from '@/components/ui/Modal';
import { Search, AlertCircle, Plus, X } from 'lucide-react';
import type { Evento } from '@/types';
import type { FunnelStage } from '@/types/settings';
import type { FunnelCard } from '@/types/funnel';
import { useMediaQuery } from '@/hooks/useMediaQuery';
import { PipelineSidebar } from '@/components/funnel/PipelineSidebar';
import { StageTabBar } from '@/components/funnel/StageTabBar';
import { LeadCard } from '@/components/funnel/LeadCard';
import { MoveStageSheet } from '@/components/funnel/MoveStageSheet';
import { motion, AnimatePresence } from 'motion/react';

export default function FunilVendas() {
  const { stageId, leadId } = useParams<{ stageId?: string; leadId?: string }>();
  const navigate = useNavigate();
  const { config, loading: configLoading } = useConfig();
  const [eventos, setEventos] = useState<Evento[]>([]);
  const [loading, setLoading] = useState(true);

  // Layout handling
  const isDesktop = useMediaQuery('(min-width: 1024px)');
  
  // Search
  const [searchTerm, setSearchTerm] = useState('');
  
  // Modals
  const [moveSheet, setMoveSheet] = useState<{isOpen: boolean, card: FunnelCard | null}>({isOpen: false, card: null});
  const [checklistModal, setChecklistModal] = useState<{isOpen: boolean, card?: FunnelCard, nextStage?: FunnelStage, blockers?: string[]}>({isOpen: false});
  const [lostModal, setLostModal] = useState<{isOpen: boolean, card?: FunnelCard, nextStage?: FunnelStage, reason?: string}>({isOpen: false, reason: 'preço'});

  // Active Stage calculation
  const activeStageId = useMemo(() => {
    if (stageId) return stageId;
    if (config.funnel_stages.length > 0) {
      const firstActive = [...config.funnel_stages].sort((a,b)=>a.order-b.order).find(s => !s.is_terminal);
      return firstActive?.id || config.funnel_stages[0].id;
    }
    return '';
  }, [stageId, config.funnel_stages]);

  // Lead selecionado para o painel lateral
  const activeLead = useMemo(() => {
    if (!leadId) return null;
    return eventos.find(e => e.id === leadId) || null;
  }, [leadId, eventos]);

  useEffect(() => {
    const q = query(collection(db, 'eventos'), orderBy('statusUpdatedAt', 'desc'));
    const unsubscribe = onSnapshot(q, (snapshot) => {
      const data = snapshot.docs.map(d => ({ id: d.id, ...d.data() } as Evento));
      setEventos(data);
      setLoading(false);
    });
    return () => unsubscribe();
  }, []);

  // Redirecionar se stageId for inválido ou se estiver em /funil sem stageId
  useEffect(() => {
    if (!configLoading && config.funnel_stages.length > 0) {
      if (!stageId) {
        const firstActive = [...config.funnel_stages].sort((a,b)=>a.order-b.order).find(s => !s.is_terminal);
        const defaultId = firstActive?.id || config.funnel_stages[0].id;
        navigate(`/funil/${defaultId}`, { replace: true });
      } else {
        const stageExists = config.funnel_stages.some(s => s.id === stageId);
        if (!stageExists) {
          navigate('/funil', { replace: true });
        }
      }
    }
  }, [configLoading, config.funnel_stages, stageId, navigate]);

  const mappedCards: FunnelCard[] = useMemo(() => {
    return eventos.map(ev => ({
      id: ev.id,
      stageId: ev.status,
      clientName: ev.clienteNome,
      clientPhone: (ev as any).clienteTelefone,
      eventType: ev.tipoEvento,
      eventDate: ev.data,
      estimatedValue: ev.valorTotal,
      allocatedRecreadorIds: ev.equipe ? ev.equipe.map((eq: any) => eq.usuarioId) : [],
      isVip: ev.valorTotal >= (config.recontact.vip_threshold_brl || 2000),
      autoGenerated: false,
      movedToCurrentStageAt: ev.statusUpdatedAt || ev.createdAt,
      createdAt: ev.createdAt,
      alerts: {
         paymentPending: !ev.restantePago && config.funnel_stages.find(s=>s.id === ev.status)?.requires_payment_check === true,
         teamMissing: isTeamAlert(ev, config),
         quoteStale: isQuoteStale(ev, config)
      },
      rawEventoInfo: ev
    }));
  }, [eventos, config]);

  const activeCards = useMemo(() => {
    return mappedCards.filter(c => 
      c.stageId === activeStageId &&
      (c.clientName.toLowerCase().includes(searchTerm.toLowerCase()) || 
       c.eventType.toLowerCase().includes(searchTerm.toLowerCase()))
    );
  }, [mappedCards, activeStageId, searchTerm]);

  const persistStageMove = async (cardId: string, nextStage: FunnelStage, extraPayload: any = {}) => {
    try {
      const payload: any = {
        status: nextStage.id,
        statusUpdatedAt: serverTimestamp(),
        ...extraPayload
      };
      await updateDoc(doc(db, 'eventos', cardId), payload);
    } catch (error) {
      console.error("Erro ao persistir mudança de Kanban:", error);
    }
  };

  const handleMoveIntent = (card: FunnelCard, targetStageId: string) => {
    const nextStage = config.funnel_stages.find(s => s.id === targetStageId);
    if (!nextStage) return;

    const blockers = getFinalizationBlockers(card.rawEventoInfo, nextStage);
    if (blockers.length > 0) {
      setChecklistModal({ isOpen: true, card, nextStage, blockers });
      return;
    }

    if (nextStage.is_terminal && nextStage.terminal_type === 'lost') {
      setLostModal({ isOpen: true, card, nextStage, reason: 'Preço/Orçamento Alto' });
      return;
    }

    persistStageMove(card.id, nextStage).finally(() => {
       setMoveSheet({isOpen: false, card: null});
    });
  };

  const handleStageSelect = (id: string) => {
    navigate(`/funil/${id}`);
  };

  const handleLeadClick = (card: FunnelCard) => {
    navigate(`/funil/${activeStageId}/${card.id}`);
  };

  const closeLeadPanel = () => {
    navigate(`/funil/${activeStageId}`);
  };

  if (configLoading) {
    return <div className="p-8">Carregando pipeline...</div>;
  }

  return (
    <div className="h-full flex flex-col lg:flex-row overflow-hidden bg-surface-base">
      
      {/* DESKTOP SIDEBAR */}
      {isDesktop && (
        <PipelineSidebar 
          stages={config.funnel_stages}
          cards={mappedCards}
          activeStageId={activeStageId}
          onStageSelect={handleStageSelect}
        />
      )}

      {/* MOBILE TABS */}
      {!isDesktop && (
        <StageTabBar 
          stages={config.funnel_stages}
          cards={mappedCards}
          activeStageId={activeStageId}
          onStageSelect={handleStageSelect}
        />
      )}

      {/* ZONA DE CONTEUDO */}
      <div className="flex-1 flex overflow-hidden relative">
        
        <div className="flex-1 flex flex-col overflow-hidden">
          {/* HEADER */}
          <div className="shrink-0 p-4 lg:p-6 lg:border-b border-surface-border-subtle bg-surface-base/50 z-10">
            <div className="flex flex-col sm:flex-row justify-between sm:items-center gap-4 mb-4">
               <div>
                  <h1 className="text-xl lg:text-2xl font-display font-bold text-text-primary capitalize">
                    {config.funnel_stages.find(s => s.id === activeStageId)?.label || 'Funil de Vendas'}
                    <span className="ml-3 text-sm font-semibold bg-surface-raised px-2 py-0.5 rounded-lg text-text-muted border border-surface-border-subtle align-middle">
                      {activeCards.length}
                    </span>
                  </h1>
                  {isDesktop && <p className="text-text-secondary text-sm mt-1">Gerencie os cards deste estágio.</p>}
               </div>
               
               {isDesktop && (
                 <Button className="gap-2 shrink-0" onClick={() => navigate('/eventos/novo')}>
                   <Plus className="w-4 h-4" /> Novo Orçamento
                 </Button>
               )}
            </div>

            <div className="relative max-w-sm">
              <Search className="w-4 h-4 absolute left-3 top-1/2 -translate-y-1/2 text-text-muted" />
              <input 
                type="text" 
                placeholder="Buscar cliente, festa..." 
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
                className="w-full pl-9 pr-4 py-2 bg-surface-raised border border-surface-border rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-brand-purple transition-all"
              />
            </div>
          </div>

          {/* LIST / GRID */}
          <div className="flex-1 overflow-y-auto custom-scrollbar p-0 lg:p-6 bg-surface-raised/20">
            {loading ? (
               <div className="flex items-center justify-center p-12"><div className="w-8 h-8 border-2 border-brand-purple border-t-transparent rounded-full animate-spin" /></div>
            ) : activeCards.length === 0 ? (
               <div className="flex flex-col items-center justify-center py-20 text-text-muted border-2 border-dashed border-surface-border rounded-2xl mx-4 lg:m-0">
                 <AlertCircle className="w-8 h-8 mb-4 opacity-20" />
                 <p className="text-sm font-bold uppercase tracking-widest opacity-60">Nenhum card neste estágio</p>
               </div>
            ) : (
              <div className={isDesktop ? "grid grid-cols-[repeat(auto-fill,minmax(300px,1fr))] gap-4" : "flex flex-col"}>
                {activeCards.map(card => (
                  <LeadCard 
                    key={card.id}
                    card={card}
                    mode={isDesktop ? 'grid' : 'list'}
                    onMoveClick={(c) => setMoveSheet({ isOpen: true, card: c })}
                    onEditClick={() => handleLeadClick(card)}
                    onWhatsAppClick={() => {}}
                  />
                ))}
              </div>
            )}
          </div>
        </div>

        {/* PANEL LATERAL DE DETALHES DO LEAD */}
        <AnimatePresence>
          {activeLead && (
            <motion.div
              initial={{ x: '100%' }}
              animate={{ x: 0 }}
              exit={{ x: '100%' }}
              transition={{ type: 'spring', damping: 25, stiffness: 200 }}
              className="absolute inset-y-0 right-0 w-full sm:w-96 bg-surface-raised border-l border-surface-border shadow-2xl z-50 flex flex-col"
            >
              <div className="p-4 border-b border-surface-border flex items-center justify-between bg-surface-base">
                <h3 className="font-bold text-text-primary">Detalhes do Lead</h3>
                <button onClick={closeLeadPanel} className="p-2 hover:bg-surface-hover rounded-lg transition-colors">
                  <X className="w-5 h-5 text-text-secondary" />
                </button>
              </div>
              <div className="flex-1 overflow-y-auto p-6 space-y-6">
                <div>
                  <label className="text-[10px] font-black text-text-muted uppercase tracking-widest block mb-1">Cliente</label>
                  <p className="text-xl font-display font-bold text-brand-purple">{activeLead.clienteNome}</p>
                </div>
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <label className="text-[10px] font-black text-text-muted uppercase tracking-widest block mb-1">Valor</label>
                    <p className="font-bold text-text-primary">{formatCurrency(activeLead.valorTotal)}</p>
                  </div>
                  <div>
                    <label className="text-[10px] font-black text-text-muted uppercase tracking-widest block mb-1">Data</label>
                    <p className="font-bold text-text-primary">{(activeLead.data as any)}</p>
                  </div>
                </div>
                <div>
                  <label className="text-[10px] font-black text-text-muted uppercase tracking-widest block mb-1">Status Atual</label>
                  <p className="px-3 py-1 bg-surface-base border border-surface-border-subtle rounded-lg text-sm font-semibold inline-block">
                    {config.funnel_stages.find(s => s.id === activeStageId)?.label}
                  </p>
                </div>
                
                <div className="pt-6 border-t border-surface-border">
                  <Button className="w-full gap-2" variant="outline" onClick={() => navigate(`/eventos/${activeLead.id}`)}>
                    Editar Cadastro Completo
                  </Button>
                </div>
              </div>
            </motion.div>
          )}
        </AnimatePresence>

        {/* MOBILE FAB */}
        {!isDesktop && (
          <button 
            onClick={() => navigate('/eventos/novo')}
            className="fixed bottom-6 right-6 z-40 w-14 h-14 rounded-full bg-brand-purple text-brand-yellow flex items-center justify-center shadow-glow-purple border border-brand-yellow/20 active:scale-95 transition-transform"
          >
             <Plus className="w-6 h-6" />
          </button>
        )}

      </div>

      {/* OVERLAYS E MODAIS */}
      <MoveStageSheet 
        isOpen={moveSheet.isOpen}
        onClose={() => setMoveSheet({isOpen: false, card: null})}
        card={moveSheet.card}
        stages={config.funnel_stages}
        onConfirm={(targetId) => { if(moveSheet.card) handleMoveIntent(moveSheet.card, targetId); }}
        isMobile={!isDesktop}
      />

      <Modal isOpen={checklistModal.isOpen} onClose={() => setChecklistModal({isOpen: false})} title="Validação Requerida">
        <div className="space-y-6">
          <div className="bg-warning/10 p-4 rounded-xl border border-warning/20">
            <p className="text-warning text-sm font-bold flex items-center gap-2">
              <AlertCircle className="w-5 h-5" /> Movimento Bloqueado
            </p>
            <p className="text-warning/80 text-xs mt-1">Este card tenta entrar num estágio terminal complexo.</p>
          </div>
          <div className="space-y-3">
             <h4 className="text-sm font-bold text-text-primary">O que falta resolver:</h4>
             {checklistModal.blockers?.map((b,i) => (
                <div key={i} className="flex items-start gap-3 p-3 bg-surface-base border border-surface-border-subtle rounded-xl text-text-primary text-sm">
                   <input type="checkbox" className="mt-0.5 rounded border-surface-border-subtle bg-surface-raised cursor-pointer" />
                   <span className="flex-1 font-medium">{b}</span>
                </div>
             ))}
          </div>
          <div className="flex gap-3 pt-4">
            <Button variant="outline" className="flex-1" onClick={() => setChecklistModal({isOpen: false})}>Cancelar</Button>
            <Button className="flex-1 shadow-glow-purple" onClick={() => {
                   if(checklistModal.card && checklistModal.nextStage) {
                      persistStageMove(checklistModal.card.id, checklistModal.nextStage).finally(()=>setChecklistModal({isOpen:false}));
                   }
                }}>Confirmo Tudo</Button>
          </div>
        </div>
      </Modal>

      <Modal isOpen={lostModal.isOpen} onClose={() => setLostModal({isOpen: false})} title="Registrar Perda">
        <div className="space-y-6">
          <p className="text-sm text-text-secondary">Poxa, uma pena! Por que este evento foi perdido?</p>
          <select 
             className="w-full bg-surface-base border border-surface-border rounded-xl p-3 text-text-primary focus:ring-2 focus:ring-brand-purple"
             value={lostModal.reason}
             onChange={e => setLostModal(prev => ({...prev, reason: e.target.value}))}
          >
             <option value="Preço/Orçamento Alto">Acharam muito caro</option>
             <option value="Data Indisponível">Nossa agenda lotada</option>
             <option value="Sem Resposta">Cliente sumiu (Ghosting)</option>
             <option value="Concorrente">Fechou com outro</option>
             <option value="Outro">Outro motivo</option>
          </select>
          <div className="flex gap-3 pt-4">
            <Button variant="outline" className="flex-1" onClick={() => setLostModal({isOpen: false})}>Cancelar</Button>
            <Button className="flex-1 bg-danger hover:bg-danger/80 text-white shadow-lg border-transparent" onClick={() => {
                   if(lostModal.card && lostModal.nextStage) {
                      persistStageMove(lostModal.card.id, lostModal.nextStage, { motivoPerda: lostModal.reason }).finally(()=>setLostModal({isOpen:false}));
                   }
              }}>Registrar Perda</Button>
          </div>
        </div>
      </Modal>

    </div>
  );
}
